package com.gome.gmp.ws.organization.pi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2016-04-12T14:07:04.213+08:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "URN:PI", name = "SI_IHR055_REQ")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SIIHR055REQ {

    @WebResult(name = "ZHR_ORGEH_MD.Response", targetNamespace = "urn:sap-com:document:sap:rfc:functions", partName = "parameters")
    @WebMethod(operationName = "SI_IHR055_REQ", action = "http://sap.com/xi/WebService/soap1.1")
    public ZHRORGEHMDResponse siIHR055REQ(
        @WebParam(partName = "parameters", name = "ZHR_ORGEH_MD", targetNamespace = "urn:sap-com:document:sap:rfc:functions")
        ZHRORGEHMD parameters
    );
}
