
package com.gome.gmp.ws.person.pi;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2016-03-22T15:20:53.084+08:00
 * Generated source version: 2.6.1
 * 
 */
public final class SIIHR053REQ_HTTPPort_Client {

    private static final QName SERVICE_NAME = new QName("URN:PI", "XI_5c31b46c3bcb350daafac27c07b60fd8_Service");

    private SIIHR053REQ_HTTPPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = XI5C31B46C3Bcb350Daafac27C07B60Fd8Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        XI5C31B46C3Bcb350Daafac27C07B60Fd8Service ss = new XI5C31B46C3Bcb350Daafac27C07B60Fd8Service(wsdlURL, SERVICE_NAME);
        SIIHR053REQ port = ss.getHTTPPort();  
        
        {
        System.out.println("Invoking siIHR053REQ...");
        com.gome.gmp.ws.person.pi.ZHRPAMD _siIHR053REQ_parameters = null;
        com.gome.gmp.ws.person.pi.ZHRPAMDResponse _siIHR053REQ__return = port.siIHR053REQ(_siIHR053REQ_parameters);
        System.out.println("siIHR053REQ.result=" + _siIHR053REQ__return);


        }

        System.exit(0);
    }

}
