package com.gome.gmp.ws.person.pi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2016-03-22T15:20:53.092+08:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "URN:PI", name = "SI_IHR053_REQ")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SIIHR053REQ {

    @WebResult(name = "ZHR_PA_MD.Response", targetNamespace = "urn:sap-com:document:sap:rfc:functions", partName = "parameters")
    @WebMethod(operationName = "SI_IHR053_REQ", action = "http://sap.com/xi/WebService/soap1.1")
    public ZHRPAMDResponse siIHR053REQ(
        @WebParam(partName = "parameters", name = "ZHR_PA_MD", targetNamespace = "urn:sap-com:document:sap:rfc:functions")
        ZHRPAMD parameters
    );
}
